#!/usr/bin/env bash
fonts="-f -*-unifont-*-*-*-*-17-*-*-*-*-*-*-* -f -*-siji-*-*-*-*-17-*-*-*-*-*-*-*"

desk() {
		desknum="$(xprop -root | grep '_NET_CURRENT_DESKTOP(CARDINAL)' | awk -F ' = ' '{print $2}')"
		toprint=""
		for i in {0..5}; do
			if [ "$i" == "$desknum" ]; then
				toprint+="%{+u}$((i + 1))%{-u}%{O5}"
			else
				toprint+="$((i + 1))%{O5}"
			fi
		done

		echo -e "${toprint}"
}

_bat() {
	stat="$(cat /sys/class/power_supply/BAT${1}/status)"
	#stat1="$(cat /sys/class/power_supply/BAT1/status)"

  bat=""
  #bat1=""

	if [[ "$stat" == "Charging" ]]; then
  	bat+="+"
	fi

	#if [[ "$stat1" == "Charging" ]]; then
  #	bat1+="+"
	#fi

	bat+="$(cat /sys/class/power_supply/BAT${1}/capacity)"
	#bat1+="$(cat /sys/class/power_supply/BAT1/capacity)"

	echo "b${1}: $bat%"
}

vol() {
  str="vol"
	if [[ $(pamixer --get-mute) == "true" ]]; then
		str+="(muted)"
	fi
	echo "${str}: $(pamixer --get-volume)%"
}

dt() {
	dt="$(cat /tmp/datetime)"
	#echo "$(eval \"${dt}\")"
	date '+%I:%M %D'
}

bri() {
  echo "bri: $(brightness)%"
}

call() {

	while true; do

		str="%{l}%{O15}$(desk)"
		str+="%{c}$(_bat 0)%{O50}$(dt)%{O50}$(_bat 1)"
		str+="%{r}$(vol)%{O10}$(bri)%{O15}"

		echo -n "${str}"
		sleep 0.3
	done
}


pkill lemonbar

echo 'date +%I:%M' > /tmp/datetime

call | lemonbar -g 1920x25 ${fonts} -F "$(pallet -x fg)" -B "$(pallet -x block)" -U "#ffffff" &
