#!/usr/bin/env bash
curr="$(cat /sys/class/backlight/intel_backlight/brightness)"
max="$(cat /sys/class/backlight/intel_backlight/max_brightness)"

real=$((100 * curr / max))
bf="/sys/class/backlight/intel_backlight/brightness"

case $1 in
	"-i") echo $(( $curr + $2)) > $bf;;
	"-d") echo $(( $curr - $2)) > $bf;;
	*) echo "$real"
esac
