#!/bin/bash
[ -z "$1" ] && {
		echo "no file specified"
		exit 1
}

# is the daemon even running?
[ -z "$(pidof emacs)" ] && emacs --daemon


# how many frames are there
nf="$(emacsclient -e '(length (visible-frame-list))')"
[ "$nf" -eq "1" ] && {
		echo "need more frame"
		emacsclient -c -n
}

emacsclient -e "(find-file \"$1\")"
